"""empty message

Revision ID: 11e50be4bafc
Revises: 46faa518903b
Create Date: 2015-09-29 19:34:10.672000

"""

# revision identifiers, used by Alembic.
revision = '11e50be4bafc'
down_revision = '46faa518903b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('order_cost', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'order_cost')
    ### end Alembic commands ###
