"""empty message

Revision ID: 1a9ad17249a2
Revises: 532e07a3ac79
Create Date: 2015-09-16 22:40:10.923000

"""

# revision identifiers, used by Alembic.
revision = '1a9ad17249a2'
down_revision = '532e07a3ac79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
