"""empty message

Revision ID: 1d85a5a9d8ce
Revises: 4bb77be10818
Create Date: 2015-09-15 18:28:27.394000

"""

# revision identifiers, used by Alembic.
revision = '1d85a5a9d8ce'
down_revision = '4bb77be10818'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('demand', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('forecast', sa.Integer(), nullable=True),
    sa.Column('received', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    ### end Alembic commands ###
