"""empty message

Revision ID: 210dd0ae1710
Revises: 3069ddf24ce3
Create Date: 2015-09-16 11:39:46.927000

"""

# revision identifiers, used by Alembic.
revision = '210dd0ae1710'
down_revision = '3069ddf24ce3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('players_scenario',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], )
    )
    op.add_column(u'players', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column(u'players', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column(u'players', 'role_id')
    op.drop_column(u'players', 'password')
    op.drop_table('players_scenario')
    op.drop_table('roles')
    ### end Alembic commands ###
