"""empty message

Revision ID: 225116af03c1
Revises: 4f66c7f649a4
Create Date: 2015-09-17 19:37:10.391000

"""

# revision identifiers, used by Alembic.
revision = '225116af03c1'
down_revision = '4f66c7f649a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_data', sa.Column('demand', sa.Integer(), nullable=True))
    op.drop_column('demand_data', 'value')
    op.drop_constraint(u'demand_profiles_scenario_id_fkey', 'demand_profiles', type_='foreignkey')
    op.drop_column('demand_profiles', 'scenario_id')
    op.add_column('scenarios', sa.Column('demand_profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenarios', 'demand_profiles', ['demand_profile_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'demand_profile_id')
    op.add_column('demand_profiles', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'demand_profiles_scenario_id_fkey', 'demand_profiles', 'scenarios', ['scenario_id'], ['id'])
    op.add_column('demand_data', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('demand_data', 'demand')
    ### end Alembic commands ###
