"""empty message

Revision ID: 22b6d9122529
Revises: 2c42bb89cf4e
Create Date: 2015-09-15 18:24:45.756000

"""

# revision identifiers, used by Alembic.
revision = '22b6d9122529'
down_revision = '2c42bb89cf4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
