"""empty message

Revision ID: 2ae8c7b8f664
Revises: cb7b4cb90ee
Create Date: 2015-09-16 16:36:11.071000

"""

# revision identifiers, used by Alembic.
revision = '2ae8c7b8f664'
down_revision = 'cb7b4cb90ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scenarios', 'players', ['owner_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='foreignkey')
    op.drop_column('scenarios', 'owner_id')
    ### end Alembic commands ###
