"""empty message

Revision ID: 2b99504ab12b
Revises: e609a1bd49
Create Date: 2015-09-15 18:32:01.725000

"""

# revision identifiers, used by Alembic.
revision = '2b99504ab12b'
down_revision = 'e609a1bd49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
