"""empty message

Revision ID: 2c42bb89cf4e
Revises: None
Create Date: 2015-09-15 18:24:03.568000

"""

# revision identifiers, used by Alembic.
revision = '2c42bb89cf4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
