"""empty message

Revision ID: 2d1aabc8cf4e
Revises: 3ac30a4e3ec5
Create Date: 2015-10-04 00:11:18.420000

"""

# revision identifiers, used by Alembic.
revision = '2d1aabc8cf4e'
down_revision = '3ac30a4e3ec5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('spot_order_cost', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'spot_order_cost')
    ### end Alembic commands ###
