"""empty message

Revision ID: 2e9c7ef46f40
Revises: 568e16c1fe
Create Date: 2015-09-16 10:33:02.809000

"""

# revision identifiers, used by Alembic.
revision = '2e9c7ef46f40'
down_revision = '568e16c1fe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_scenario',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], )
    )
    op.add_column(u'gameboards', sa.Column('data', sa.PickleType(), nullable=True))
    op.drop_column(u'gameboards', 'tablestring')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'gameboards', sa.Column('tablestring', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column(u'gameboards', 'data')
    op.drop_table('players_scenario')
    ### end Alembic commands ###
