"""empty message

Revision ID: 3069ddf24ce3
Revises: 2e9c7ef46f40
Create Date: 2015-09-16 10:41:33.426000

"""

# revision identifiers, used by Alembic.
revision = '3069ddf24ce3'
down_revision = '2e9c7ef46f40'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboards', sa.Column('tablestring', sa.PickleType(), nullable=True))
    op.drop_column('gameboards', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboards', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('gameboards', 'tablestring')
    ### end Alembic commands ###
