"""empty message

Revision ID: 338ceb99223d
Revises: 22b6d9122529
Create Date: 2015-09-15 18:24:51.756000

"""

# revision identifiers, used by Alembic.
revision = '338ceb99223d'
down_revision = '22b6d9122529'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
