"""empty message

Revision ID: 3438e3a98098
Revises: 2d1aabc8cf4e
Create Date: 2015-10-04 20:48:00.102000

"""

# revision identifiers, used by Alembic.
revision = '3438e3a98098'
down_revision = '2d1aabc8cf4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('selling_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'selling_price')
    ### end Alembic commands ###
