"""empty message

Revision ID: 344e0e5733b7
Revises: 855f9000758
Create Date: 2015-09-20 09:34:50.794000

"""

# revision identifiers, used by Alembic.
revision = '344e0e5733b7'
down_revision = '855f9000758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_profiles', sa.Column('periods', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand_profiles', 'periods')
    ### end Alembic commands ###
