"""empty message

Revision ID: 37d0127f7699
Revises: 344e0e5733b7
Create Date: 2015-09-20 09:59:35.775000

"""

# revision identifiers, used by Alembic.
revision = '37d0127f7699'
down_revision = '344e0e5733b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'demand_profiles', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demand_profiles', type_='unique')
    ### end Alembic commands ###
