"""empty message

Revision ID: 3a4bd264f6f7
Revises: 44c89ad64bac
Create Date: 2015-09-16 12:49:48.121000

"""

# revision identifiers, used by Alembic.
revision = '3a4bd264f6f7'
down_revision = '44c89ad64bac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'scenarios', ['code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='unique')
    op.drop_column('scenarios', 'code')
    ### end Alembic commands ###
