"""empty message

Revision ID: 3ac30a4e3ec5
Revises: 11e50be4bafc
Create Date: 2015-10-02 09:07:01.192000

"""

# revision identifiers, used by Alembic.
revision = '3ac30a4e3ec5'
down_revision = '11e50be4bafc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('spot_cost', sa.Float(), nullable=True))
    op.add_column('scenarios', sa.Column('spot_leadtime', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('spot_min_lotsize', sa.Integer(), nullable=True))
    op.add_column('scenarios', sa.Column('spot_yield', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'spot_yield')
    op.drop_column('scenarios', 'spot_min_lotsize')
    op.drop_column('scenarios', 'spot_leadtime')
    op.drop_column('scenarios', 'spot_cost')
    ### end Alembic commands ###
