"""empty message

Revision ID: 416925f7a48c
Revises: 1a9ad17249a2
Create Date: 2015-09-17 08:40:38.226000

"""

# revision identifiers, used by Alembic.
revision = '416925f7a48c'
down_revision = '1a9ad17249a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_profile_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('forecast', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('scenario_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_code',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'scenario_code_pkey'),
    sa.UniqueConstraint('code', name=u'scenario_code_code_key')
    )
    op.drop_table('scenario_codes')
    op.drop_table('demand_profiles')
    op.drop_table('demand_data')
    ### end Alembic commands ###
