"""empty message

Revision ID: 44c89ad64bac
Revises: 210dd0ae1710
Create Date: 2015-09-16 12:40:19.306000

"""

# revision identifiers, used by Alembic.
revision = '44c89ad64bac'
down_revision = '210dd0ae1710'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('status', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'status')
    ### end Alembic commands ###
