"""empty message

Revision ID: 456c181a7a96
Revises: 1bf2fe3d3ca2
Create Date: 2015-09-26 14:33:24.690000

"""

# revision identifiers, used by Alembic.
revision = '456c181a7a96'
down_revision = '1bf2fe3d3ca2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_profiles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('demand_profiles', sa.Column('initial_stock', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand_profiles', 'initial_stock')
    op.drop_column('demand_profiles', 'description')
    ### end Alembic commands ###
