"""empty message

Revision ID: 49d36e4263dd
Revises: 2dad18d26cdb
Create Date: 2015-09-16 22:15:00.481000

"""

# revision identifiers, used by Alembic.
revision = '49d36e4263dd'
down_revision = '2dad18d26cdb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboards', sa.Column('table', sa.PickleType(), nullable=True))
    op.drop_column('gameboards', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameboards', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('gameboards', 'table')
    ### end Alembic commands ###
