"""empty message

Revision ID: 4bb77be10818
Revises: 338ceb99223d
Create Date: 2015-09-15 18:25:45.538000

"""

# revision identifiers, used by Alembic.
revision = '4bb77be10818'
down_revision = '338ceb99223d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
