"""empty message

Revision ID: 532e07a3ac79
Revises: 49d36e4263dd
Create Date: 2015-09-16 22:27:13.639000

"""

# revision identifiers, used by Alembic.
revision = '532e07a3ac79'
down_revision = '49d36e4263dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
