"""empty message

Revision ID: 561323c9fdab
Revises: 2ae8c7b8f664
Create Date: 2015-09-16 16:37:23.781000

"""

# revision identifiers, used by Alembic.
revision = '561323c9fdab'
down_revision = '2ae8c7b8f664'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('activation_date', sa.DateTime(), nullable=True))
    op.add_column('scenarios', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('scenarios', sa.Column('run_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'run_date')
    op.drop_column('scenarios', 'creation_date')
    op.drop_column('scenarios', 'activation_date')
    ### end Alembic commands ###
