"""empty message

Revision ID: 568e16c1fe
Revises: 2406e56992ca
Create Date: 2015-09-16 09:11:25.492000

"""

# revision identifiers, used by Alembic.
revision = '568e16c1fe'
down_revision = '2406e56992ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('tablestring', sa.PickleType(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('decisions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('demand', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('forecast', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], [u'players.id'], name=u'decisions_player_id_fkey'),
    sa.ForeignKeyConstraint(['scenario_id'], [u'scenarios.id'], name=u'decisions_scenario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'decisions_pkey')
    )
    op.drop_table('gameboards')
    ### end Alembic commands ###
