"""empty message

Revision ID: 855f9000758
Revises: 225116af03c1
Create Date: 2015-09-17 20:53:12.138000

"""

# revision identifiers, used by Alembic.
revision = '855f9000758'
down_revision = '225116af03c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand_data', sa.Column('error', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand_data', 'error')
    ### end Alembic commands ###
