"""empty message

Revision ID: cb7b4cb90ee
Revises: 3a4bd264f6f7
Create Date: 2015-09-16 16:04:16.123000

"""

# revision identifiers, used by Alembic.
revision = 'cb7b4cb90ee'
down_revision = '3a4bd264f6f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_code')
    ### end Alembic commands ###
