"""empty message

Revision ID: e609a1bd49
Revises: 1d85a5a9d8ce
Create Date: 2015-09-15 18:29:37.301000

"""

# revision identifiers, used by Alembic.
revision = 'e609a1bd49'
down_revision = '1d85a5a9d8ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
